/*
 * This file was automatically generated by EvoSuite
 * Thu Jan 22 21:49:35 GMT 2026
 */

package com.bank;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.bank.Account;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal((-2321));
      // Undeclared exception!
      try { 
        account0.withdraw(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal((-1826L));
      // Undeclared exception!
      try { 
        account0.deposit(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal(731);
      BigDecimal bigDecimal1 = bigDecimal0.scaleByPowerOfTen(1459);
      account0.deposit(bigDecimal0);
      account0.withdraw(bigDecimal0);
      account0.deposit(bigDecimal1);
      account0.withdraw(bigDecimal0);
      BigDecimal bigDecimal2 = account0.getBalance();
      assertEquals((short) (-731), bigDecimal2.shortValue());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal(2972);
      account0.deposit(bigDecimal0);
      BigDecimal bigDecimal1 = account0.getBalance();
      assertEquals((short)2972, bigDecimal1.shortValue());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Account account0 = new Account();
      // Undeclared exception!
      try { 
        account0.deposit((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Dep\u00F3sito inv\u00E1lido
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Account account0 = new Account();
      // Undeclared exception!
      try { 
        account0.withdraw((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Saque inv\u00E1lido
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = account0.getBalance();
      // Undeclared exception!
      try { 
        account0.withdraw(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      // Undeclared exception!
      try { 
        account0.withdraw(bigDecimal0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Saldo insuficiente
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = account0.getBalance();
      // Undeclared exception!
      try { 
        account0.deposit(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }
}
